//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ceya.Infrastructure.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ceya.Infrastructure.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio que el Presupuesto tenga un Cliente asignado..
        /// </summary>
        internal static string ClienteRequired {
            get {
                return ResourceManager.GetString("ClienteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible asignar un Código en el alta de un Presupuesto..
        /// </summary>
        internal static string CodigoNotRequired {
            get {
                return ResourceManager.GetString("CodigoNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Estado de un nuevo Presupuesto no puede ser otro al Inicial (Presupuestado).
        /// </summary>
        internal static string EstadoNotRequired {
            get {
                return ResourceManager.GetString("EstadoNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ID de transacción del Presupuesto no puede ser cero..
        /// </summary>
        internal static string InvalidEmptyTransaccion {
            get {
                return ResourceManager.GetString("InvalidEmptyTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Item del Presupuesto no puede contener el estado que se le ha asignado..
        /// </summary>
        internal static string InvalidItemState {
            get {
                return ResourceManager.GetString("InvalidItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Item de Presupuesto con el ID especificado..
        /// </summary>
        internal static string ItemExists {
            get {
                return ResourceManager.GetString("ItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el Item de referencia en el Presupuesto..
        /// </summary>
        internal static string ItemNotExists {
            get {
                return ResourceManager.GetString("ItemNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio que el Presupuesto tenga una Obra asignada..
        /// </summary>
        internal static string ObraRequired {
            get {
                return ResourceManager.GetString("ObraRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el Presupuesto con el código especificado..
        /// </summary>
        internal static string PresupuestoExiste {
            get {
                return ResourceManager.GetString("PresupuestoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el Presupuesto con el código especificado..
        /// </summary>
        internal static string PresupuestoNoExiste {
            get {
                return ResourceManager.GetString("PresupuestoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar esta revisión del Presupuesto..
        /// </summary>
        internal static string PresupuestoRevisionNoActualizable {
            get {
                return ResourceManager.GetString("PresupuestoRevisionNoActualizable", resourceCulture);
            }
        }
    }
}
