// <auto-generated />
namespace ceya.Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregadodecolocacionIdyvidrioId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregadodecolocacionIdyvidrioId));
        
        string IMigrationMetadata.Id
        {
            get { return "201711190003138_agregado de colocacionId y vidrioId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
