// <auto-generated />
namespace ceya.Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nulleablecodigorubro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nulleablecodigorubro));
        
        string IMigrationMetadata.Id
        {
            get { return "201711150229192_nulleable codigorubro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
