// <auto-generated />
namespace ceya.Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixCyclicFkSubrubro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCyclicFkSubrubro));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300437085_FixCyclicFkSubrubro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
