// <auto-generated />
namespace ceya.Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nulleabletipodocumento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nulleabletipodocumento));
        
        string IMigrationMetadata.Id
        {
            get { return "201801172034369_nulleable tipodocumento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
